# Generated by Django 4.2.6 on 2025-04-25 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintmanagement',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='folder',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='workspace.workspace'),
        ),
    ]
