# Generated by Django 4.2.6 on 2025-04-21 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_sprintmanagement_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintmanagement',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
