# Generated by Django 4.2.6 on 2025-04-21 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0004_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintmanagement',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='sprint.folder'),
        ),
    ]
