# Generated by Django 4.2.6 on 2025-04-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        ('sprint', '0005_sprintmanagement_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintmanagement',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='workspace.workspace'),
        ),
    ]
