# Generated by Django 4.2.6 on 2025-04-22 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0006_sprintmanagement_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintmanagement',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
