# Generated by Django 4.2.6 on 2025-04-18 05:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('todo', 'TODO'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
