# Generated by Django 4.2.6 on 2025-04-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0001_initial'),
        ('todolist', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sprints',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='sprint.sprintmanagement'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('need_to_discuss', 'Need to Discuss'), ('reopen', 'Reopen'), ('waiting_to_be_merged', 'Waiting to be Merged'), ('complete', 'Complete')], default='todo', max_length=20),
        ),
    ]
