# Generated by Django 5.2 on 2025-04-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_taskview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskView',
        ),
    ]
