# Generated by Django 5.2 on 2025-05-06 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_task_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='to_users',
            field=models.ManyToManyField(related_name='email_comment_recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
