# Generated by Django 5.2 on 2025-05-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_comment_content_comment_to_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
