# Generated by Django 4.2.6 on 2025-04-25 09:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace_name', models.CharField(max_length=255, unique=True)),
                ('workspace_type', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('school', 'School')])),
                ('manage_type', models.CharField(choices=[('hr_recruiting', 'HR & Recruiting'), ('marketing', 'Marketing'), ('it', 'IT'), ('personal_use', 'Personal Use'), ('pmo', 'PMO'), ('professional_services', 'Professional Services'), ('software_development', 'Software Development'), ('support', 'Support'), ('startup', 'Startup'), ('operations', 'Operations'), ('sales_crm', 'Sales & CRM'), ('others', 'Others')])),
                ('resource', models.CharField(choices=[('linkedin', 'LinkedIn'), ('tv', 'TV'), ('youtube', 'YouTube'), ('google', 'Google'), ('facebook', 'Facebook'), ('friends/colleagues', 'Friends & Colleagues'), ('reddit', 'Reddit'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('software review site', 'Software Review site'), ('search engines(google, bing)', 'Search Engines (Google, bing)'), ('others', 'Others')], max_length=255)),
                ('tools', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('dropbox', 'Dropbox'), ('monday', 'Monday'), ('basecamp', 'Basecamp'), ('salesforce', 'Salesforce'), ('trello', 'Trello'), ('todolist', 'Todoist'), ('jira', 'Jira'), ('gdrive', 'Google Drive'), ('figma', 'Figma'), ('github', 'GitHub'), ('slack', 'Slack'), ('ms_teams', 'MS Teams'), ('excel_csv', 'Excel & CSV'), ('asana', 'Asana')]), size=None)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('docs_wikis', 'Docs & Wikis'), ('sprints', 'Sprints'), ('calendar', 'Calendar'), ('goals_okrs', 'Goals & OKRs'), ('clips', 'Clips'), ('boards', 'Boards'), ('dashboard', 'Dashboard'), ('chat', 'Chat'), ('time_tracking', 'Time Tracking'), ('crm', 'CRM'), ('automations', 'Automations'), ('ask_ai', 'Ask AI'), ('scheduling', 'Scheduling'), ('tasks_projects', 'Tasks & Projects'), ('whiteboards', 'Whiteboards')], max_length=255), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('invited_on', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
