# Generated by Django 4.2.6 on 2025-04-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
